config/routes.rb
Rails.application.routes.draw do

  devise_for  :users, 
              :controllers => {
             #     sessions: "mydevise/sessions",
                  registrations: "mydevise/registrations"
              } 
          #    :skip => [:sessions] do
           #     get '/users/sign_in' => 'sessions#new', :as => :new_user_session
            #    post '/users/sign_in' => 'sessions#create', :as => :user_session
             #   get '/users/sign_out' => 'sessions#destroy', :as => :destroy_user_session
             # end
  resources :users, path: "user", only: [:index, :show, :destroy, :update] do
    match 'recipebook', to: 'users#recipebook', via: :get
    get '/users/sign_out' => 'devise/sessions#destroy'
    #resources :comments
  end


  resources :directions, only: [:create, :destroy, :update]

  resources :cooks do 
    resources :recipes
  end

  root "welcome#index"

  match 'add_like_recipe', to: 'like_recipes#like_recipe', via: :post
  match 'unlike_recipe', to: 'like_recipes#unlike_recipe', via: :delete
  match 'recipes', to: 'recipes#browse_recipes', via: :post
  #match 'myrecipes', to: 'recipes#my_recipes', via: :get

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	
	attr_accessor :distance, :in_range

	belongs_to :cook
	belongs_to :dishtype

	has_many :ingredients
	has_many :directions
	has_many :like_recipes, dependent: :destroy
	has_many :users, through: :like_recipes

	has_attached_file :image, styles: { medium: "300x300#", thumb: "200x200#" }

	validates_presence_of :cook_id, :stars, :title, :intro, :description, :duration, :stars
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	accepts_nested_attributes_for 	:ingredients, 
									:reject_if => proc { |attributes| attributes['name'].blank? }, 
									:allow_destroy => true
	accepts_nested_attributes_for 	:directions, 
									:reject_if => :all_blank, 
									:allow_destroy => true

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

	before_action :find_recipe, only: [:show, :update, :edit, :destroy]
	before_action :find_cook, only: [:index, :create, :show]

	def index
		find_cook
		@recipes = @cook.recipes.order("created_at DESC")
	end

	def browse_recipes
		if params[:lat] == "no"
			@recipes = Recipe.all.order("created_at DESC")
		else
			search_recipes([params[:lat], params[:lng]])
		end
		message
		flash.now[:notice] = @message
	end

	def show
		@directions = Direction.where(recipe_id: @recipe.id).order("rank ASC")
		get_rank_list()
		get_dishtype_list()
		@nb_votes = 0
		@nb_liked = current_user.nb_liked?
	end

	def create
		@recipe = @cook.recipes.build(
			title: "Recette " + (@cook.recipes.count + 1).to_s, 
			intro: 'Introduction',
			description: 'Description',
			duration: 10, 
			stars: 0,
			dishtype_id: 0)

		if @recipe.save
			redirect_to [@cook, @recipe], notice: "La nouvelle recette est créée"
		else
			redirect_to current_user, notice: "Impossible de créer la recette"
		end
	end

	def edit
	end

	def update
		params[:duration].to_i
		respond_to do |format|
	      if @recipe.update(recipe_params)
	        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
	        format.json { head :no_content }
	      else
	        format.html { render action: 'edit' }
	        format.json { render json: @recipe.errors, status: :unprocessable_entity }
	      end
	    end

	end

	def destroy
		@recipe.destroy
		redirect_to user_path(current_user), notice: "La recette a bien été supprimée"
	end

	private 

	def recipe_params
		params.require(:recipe).permit(	:title, :description, :duration, :image, :dish_type,:dist, :in_range,
										ingredients_attributes: [:id, :name, :_destroy],
										directions_attributes: [:id, :step, :_destroy],
										)
	end

	def find_recipe
		@recipe = Recipe.find(params[:id])
	end

	def find_cook
		@cook = Cook.friendly.find(params[:cook_id])
	end

	def search_recipes(coordinates)
		search_cooks(coordinates)
		@recipes = Array.new
		@cooks.each do |cook|
			cook.recipes.each do |recipe|
				recipe.distance = cook.distance
				recipe.in_range = cook.in_range
				@recipes << recipe
			end
		end
	end

	def message
		if params[:lat] == "no" && @recipes.empty?
			@message = "Aucune recette dans la BDD : initialisation nécessaire"
		elsif params[:lat] == "no"
			@message = @recipes.count.to_s + " recette".pluralize(@recipes.count) + " trouvée".pluralize(@recipes.count)
		elsif @recipes.empty?
			@message = "Aucune recette n'a été trouvée autour de cette addresse..."
	    elsif
			@message = @recipes.count.to_s + " recette".pluralize(@recipes.count) + " trouvée".pluralize(@recipes.count) + " autour de cette adresse..."
			@recipes = @recipes.sort_by { |v| v.distance }
	    end
	end	

end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_direction_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :step, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button"

app/views/recipes/_form.html.haml
= simple_form_for @recipe, html: { multipart: true } do |f|
	- if @recipe.errors.any?
		#errors
			%p
				= @recipe.errors.count
				blocked the saving
			%u1
				- @recipe.errors.full_message.each do |msg|
					%li = msg
	.panel-body
		= f.collection_select :dishtype_id, Dishtype.all, :id, :name, {prompt: "Choose a type of Dish" }
		= f.input :title, input_html: { class: 'form-control'}
		= f.input :description, input_html: {class: 'form-control'}
		= f.input :image, input_html: {class: 'form-control'}

		.row
			.col-md-6
				%h3 Ingredients
				#ingredients
					= f.simple_fields_for :ingredients do |ingredient|
						= render 'ingredient_fields', f: ingredient
					.links
						= link_to_add_association 'Add ingredient', f, :ingredients, class: "btn btn-default add-button"
			.col-md-6
				%h3 Directions
				#directions
					= f.simple_fields_for :directions do |direction|
						= render 'direction_fields', f: direction
					.links
						= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button"


	= f.button :submit, class: 'btn btn-primary'
	= link_to "Back", users_path

app/views/recipes/_ingredient_fields.html.haml
.form-inline.clearfix
	.nested-fields
		= f.input :name, input_html: { class: 'form-input form-control' }
		= link_to_remove_association "Remove", f, class: "btn btn-default form-button"

app/views/recipes/_recipes_list.html.haml
.row
	.col-xs-6.col-md-8
		- if @adress.present?
			.adress_area
				%h4=@adress
				= link_to cooks_path do
					= image_tag "icons/cross.png", class: "logo_field"
	.col-xs-6.col-md-4
		.row
			.col-xs-3	
				%h4= "trier par :"
			.col-xs-3	
				%h4=link_to "note", id: "sort_note"
			.col-xs-3	
				%h4=link_to "type de plat", id: "sort_dishtype"
			.col-xs-3	
				%h4=link_to "durée", id: "sort_duration"
#recipe_results
	- @recipes.each_slice(4) do |slice|
		.row
			- @recipes.each do |recipe|
				.col-md-4
					.recipe
						=link_to cook_recipe_path(recipe.cook.id, recipe) do
							%h2= recipe.title
							= @nb_votes.to_s + " votes"	
							- recipe.stars.to_i.times do 
								= image_tag "icons/star.png"
							.image_wrapper
								=image_tag recipe.image.url(:thumb)
							%h5= recipe.intro
							%h5= recipe.duration.to_s + " min"
							%h5= recipe.dishtype_id


:javascript
	$('#sort_note').click(function() {
		$('#modif_account').hide();
		$('#modif_account_form').show();
	});

app/views/recipes/browse_recipes.html.haml
= render :partial => 'shared/searchbar'

.row


	.col-xs-12.recipes_area
		.row
			.title
				%h1= "Les recettes"
		= render :partial => 'recipes_list', recipes: @recipes

app/views/recipes/edit.html.haml
%h1 Edit recipe

= render 'form'

app/views/recipes/index.html.haml
.row
	.col-xs-12.col-sm-4.col-md-2.cook_area
		= render :partial => 'cooks/cook_preview', cook: @cook
	.col-xs-12.col-sm-8.col-md-10.recipes_area
		.row
			.title
				%h1= "Les recettes de " + @cook.title
		= render :partial => 'recipes_list', recipes: @recipes
		

app/views/recipes/like_recipe.js.erb
$('#like_recipe_button').html('<%= j render partial: "like_recipe_button", locals: { recipe: @recipe } %>');

app/views/recipes/my_recipes.html.haml
= render :partial => 'shared/searchbar'

.row


	.col-xs-12.recipes_area
		.row
			.title
				%h1= "Mes recettes"
		= render :partial => 'recipes_list', recipes: @recipes

app/views/recipes/new.html.haml
%h1 New recipe

= render 'form'

%br/

//= link_to "Back", root_path, class='btn btn-default'

app/views/recipes/show.html.haml
.row
	.title_bar
		.col-xs-4.col-md-3.head
			= image_tag "tete.png"
			%h5= @cook.title
		.col-xs-4.col-md-6.title
			.recipe_title
				%h2= editable [@cook, @recipe], :title, value: @recipe.title
			- if user_signed_in? && current_user.id == @cook.user_id
				= link_to "Supprimer la recette", cook_recipe_path, method: :delete, data: {confirm: "Etes vous sûr de vouloir supprimer cette recette ?"}
			= pluralize(@nb_votes, 'vote')	
			- @recipe.stars.to_i.times do 
				= image_tag "icons/star.png"
		.col-xs-4.col-md-3.icons
			= image_tag "icons/recipes/email.png"
			= image_tag "icons/recipes/print.png"
			- if user_signed_in? && current_user.id == @cook.user_id
				#btn_modify
					= image_tag "icons/recipes/edit_recipe.png"
			- if user_signed_in? && current_user.id != @cook.user_id
				#like_recipe_button
					= render partial: 'like_recipes/like_recipe_button', locals: { recipe: @recipe, nb_liked: @nb_liked }

.row
	.col-xs-12.col-sm-6.block_left
		.image_wrapper
			= image_tag "samosas.jpg"
			=#@recipe.image.url(:thumb)
		.recipe_description
			%h5= editable [@cook, @recipe], :description, value: @recipe.description
		.col-xs-6.ingredients
			%h5 Ingrédients (4 pers)
			%h5 liste des ingrédients
		.col-xs-6.material
			%h5 Matériel nécessaire
			%h5 liste des matériels

	.col-xs-12.col-sm-6.blocl_right
		%h3 Recette
		= image_tag "icons/time.png"
		.recipe_duration
			%h5= editable [@cook, @recipe], :duration, value: @recipe.duration.to_s
		.dishtype
			%h2= editable [@cook, @recipe], :dishtype_id, type: "select", title: "Type de plat", value: @recipe.dishtype_id, source: @dishtype_list
		
		#directions.directions
			= render :partial => 'shared/directions', directions: @directions, rank_list: @rank_list
		
		- if user_signed_in? && current_user.id == @cook.user_id
			= link_to("Ajouter une étape", directions_path(direction:{"step"=>"à compléter", "recipe_id"=>@recipe.id}), method: :post, remote: true, :class => 'add_direction')

:javascript
	$(document).ready(function() {
		$('.editable').editable('disable');
	});
	$("#btn_modify").click(function() {
		$('.editable').editable('toggleDisabled');
	});

app/views/recipes/unlike_recipe.js.erb
$('#like_recipe_button').html('<%= j render partial: "like_recipe_button", locals: { recipe: @recipe } %>');