config/routes.rb
Rails.application.routes.draw do

  devise_for  :users, 
              :controllers => {
             #     sessions: "mydevise/sessions",
                  registrations: "mydevise/registrations"
              } 
          #    :skip => [:sessions] do
           #     get '/users/sign_in' => 'sessions#new', :as => :new_user_session
            #    post '/users/sign_in' => 'sessions#create', :as => :user_session
             #   get '/users/sign_out' => 'sessions#destroy', :as => :destroy_user_session
             # end
  resources :users, path: "user", only: [:index, :show, :destroy, :update] do
    match 'recipebook', to: 'users#recipebook', via: :get
    get '/users/sign_out' => 'devise/sessions#destroy'
    #resources :comments
  end


  resources :directions, only: [:create, :destroy, :update]

  resources :cooks do 
    resources :recipes
  end

  root "welcome#index"

  match 'add_like_recipe', to: 'like_recipes#like_recipe', via: :post
  match 'unlike_recipe', to: 'like_recipes#unlike_recipe', via: :delete
  match 'recipes', to: 'recipes#browse_recipes', via: :post
  #match 'myrecipes', to: 'recipes#my_recipes', via: :get

end

app/views/shared/_cook_preview.html.haml
= image_tag(@user.avatar.url)
= link_to @cook.title, cook_recipes_path(@cook)
= @cook.nb_stars
= @cook.nb_avis.to_s + ' avis'
#btn_contact
	= link_to 'contact', ''
= @cook.locality + ' + ' + @cook.working_distance + ' km'
= 'Langues : ' + @cook.nb_languages.to_s
= @cook.price.to_s + ' / pers'
= @cook.introduction
= @cook.phone_number
= @cook.verified_phone
= @cook.user.email


:javascript
	$(document).ready(function() {
	 	$('#contact').hide();
	});
	$("#btn_contact").click(function() {
		$('#contact').show();
	});

app/views/shared/_directions.html.haml
- @directions.each do |direction|
	.direction{:id => "direction_#{direction.id}"}
		%h5= editable direction, :rank, type: "select", title: "Rang", value: direction.rank, source: @rank_list
		%h5= editable direction, :step, value: direction.step
		= link_to direction_path(direction), method: :delete, :remote => true, :class => 'delete_direction' do
			= image_tag "icons/cross.png", class: "logo_field"

:javascript
	$('.editable').editable('disable');

app/views/shared/_flash_display.haml
- if notice
	.notice 
		= message
- if alert
	.alert 
		= message
- if info
	.alert 
		= message

app/views/shared/_modal_accounts.html.haml
#account.modal						
	.modal-content.no-hide
		#connect-account
			.modal-header
				%h3.modal-title="Log in"
				%span.close= 'X'
			.modal-body
				= form_tag session_path(:user), html: { autocomplete: "off" }, class: 'form-center' do
					= text_field_tag 'user[email]', nil, required: 'true', placeholder: 'Email'
					= password_field_tag 'user[password]', nil, required: 'true', placeholder: 'Password'
					= link_to "Mot de passe oublié ?", new_password_path(:user), class: "forgot"
					%button.btn-account Sign in
			.link-new-user
				%h3= "Pas encore inscrit ?"
				= navbar_text 'Créer mon compte', id: "create_account", class: "register-link"
		#create-account
			.modal-header
				%h3.modal-title="Nouveau compte"
				%span.close= 'X'
			.modal-body
				= form_tag registration_path(:user), html: { autocomplete: "off" }, class: 'form-center' do
					= text_field_tag 'user[email]', nil, required: true, placeholder: 'Email'
					= text_field_tag 'user[pseudo]', nil, required: true, placeholder: 'Pseudo'
					= password_field_tag 'user[password]', nil, required: true, placeholder: 'Password'
					= password_field_tag 'user[password_confirmation]', nil, required: true, placeholder: 'Confirm password'
					%button.btn-account Créer le compte
			.link-new-user
				%h3= "Déjà inscrit ?"
				= navbar_text 'log in', id: "connect_account", class: "register-link"

:javascript

	// When the user clicks on <span> (x), close the modal
	$('#close').click(function() {
		$('#account').fadeOut("slow");
	});

	// When the user clicks anywhere outside of the modal, close it
	$(window).on("click", function(event) {
		if ((!$(event.target).parents('.no-hide').length || $(event.target).is(".close")) && !$(event.target).is(".no-hide")) {
			$('#account').fadeOut("slow");
		}
	});

	$('#create_account').click(function() {
		$('#connect-account').hide();
		$('#create-account').show();
	});

	$('#connect_account').click(function() {
		$('#create-account').hide();
		$('#connect-account').show();
	});

app/views/shared/_my_account.html.haml
%h1='Mon compte'
.row
	.col-xs-6
		.row
			#account_details
				%h5='Votre pseudo (affiché sur le site) : ' + @user.pseudo
				%h5='Votre email (non affiché sur le site) : ' + @user.email
				= image_tag(@user.avatar.url)
				=link_to "Modifier le compte", '', remote: true, class: 'btn btn-info', id: "modif_account"

			#account_form
				= render partial: 'users/shared/change_account', user: @user
		.row
			#btn_modify
				= image_tag "icons/edit.png"
			



	.col-xs-6
		.row
			.col-xs-6
				%h4 Mon book de recettes
				= pluralize(@nb_like, ' recette')
			.col-xs-6
				- if @user.nb_liked > 0
					= link_to "Vider", like_recipe_path, data: { confirm: "Vider votre book ?" }, method: :delete, class: 'btn btn-danger'
		.row
			- if @new_cook == false
				=link_to "Créer une recette", cook_recipes_path(@cook.id), method: :post, class: 'btn btn-info'
.row
	- if @new_cook == true
		%h3='Devenez cook et partagez votre talent !'
		=link_to "Devenir cook", "", remote: true, class: 'btn btn-info', id: "become_cook"

		#cook_form
			= form_for @cook do |f|
				%h5= "Titre du cook :"
				= f.text_field :title, required: true
				%h5= "Gendre :"
				= f.select :gender, options_for_select(["Homme","Femme"]) 
				%h5= "Introduction :"
				= f.text_field :introduction
				%h5= "Téléphone de contact :"
				= f.text_field :phone_number
				%h5= text_field_tag :address, 'address', value: '', placeholder: 'Mon adresse', class: ''
				%h5= "Distance de travail :"
				= f.select :working_distance, options_for_select(["5","10","15","20","25","30","35","40","45","50"]) 
				= f.hidden_field :lat, "data-geo"=>"lat", required: true
				= f.hidden_field :lng, "data-geo"=>'lng', required: true
				= f.hidden_field :formatted_address, "data-geo"=>'formatted_address', required: true
				= f.hidden_field :street_number, "data-geo"=>'street_number'
				= f.hidden_field :route, "data-geo"=>'route'	
				= f.hidden_field :locality, "data-geo"=>'locality', required: true
				= f.text_field :postal_code, readonly: :true, "data-geo"=>'postal_code', required: true
				= f.hidden_field :administrative_area_level_1, "data-geo"=>'administrative_area_level_1', required: true		
				= f.hidden_field :country, "data-geo"=>'country', required: true
				= submit_tag "Activer mon cook", class: 'btn btn-info'
				= link_to "Annuler", "", remote: true, class: 'btn btn-danger', id: "cancel_cook"
	- else
		%h5='Détails de mon cook'
		%h5='Titre du cook : '
		%h5= editable @cook, :title, value: @cook.title
		=link_to "Désactiver mon cook", cook_path(@cook), method: :delete, data: {confirm: "Votre cuisinier et toutes vos recettes seront supprimées ! Etes-vous sûr ?"}, class: 'btn btn-danger'
		%h5='Sexe : '
		%h5= editable @cook, :gender, value: @cook.gender 
		%h5='Introduction : '
		%h5= editable @cook, :introduction, value: @cook.introduction
		%h5='Téléphone de contact : '
		%h5= editable @cook, :phone_number, value: @cook.phone_number
		- if @cook.verified_phone == true
			= image_tag "process/icons/ok.png", class: "logo_process"
			%h5 Numéro vérifié
		%h5='Localisation : '
		%h5= @cook.formatted_address
		%h5='Distance de travail : '
		%h5= editable @cook, :working_distance, value: @cook.working_distance
		%h5=' km'

		=link_to pluralize(@recipes.count, 'recette proposée'), cook_recipes_path(@cook)
		- @recipes.each do |recipe|
			=link_to recipe.title, [@cook, recipe]



:javascript
	$(document).ready(function() {
		$('.editable').editable('disable');
	 	$('#cook_form').hide();
	 	$('#account_form').hide();
	 	$('#btn_modify').hide();
	});
	$("#btn_modify").click(function() {
		$('.editable').editable('toggleDisabled');
	});
	$('#modif_account').click(function() {
		$('#account_details').hide();
		$('#account_form').show();
	});
	$('#cancel_account_modif').click(function() {
		$('#account_form').hide();
		$('#account_details').show();
	});	
	$('#become_cook').click(function() {
		$('#cook_form').show();
		$('#become_cook').hide();
	});
	$('#cancel_cook').click(function() {
		$('#cook_form').hide();
		$('#become_cook').show();
	});
	

app/views/shared/_new_account.html.haml
= form_for(@user, url: registration_path(:user)) do |f|
	= f.error_notification
	= f.input :email, required: true, autofocus: true, input_html: { class: 'form-control' }
	= f.text_field :pseudo, required: true
	= f.input :password, required: true, input_html: { class: 'form-control' }, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length)
	= f.input :password_confirmation, required: true, input_html: { class: 'form-control' }

	= f.button :submit, "Créer le compte", class: "btn btn-primary"

app/views/shared/_searchbar.html.haml
#search_bar.row
	.col-xs-4.col-sm-3.col-md-2
		= form_tag cooks_path, :method => :get do
			= hidden_field_tag(:lat, "no", "data-geo"=>"lat", required: true)
			= hidden_field_tag(:lng, "no", "data-geo"=>"lng", required: true)
			= hidden_field_tag(:formatted_address, "no", "data-geo"=>"formatted_address", required: true)
			= submit_tag "VOIR LES COOKS", :name => nil, class: 'btn_search_cook_green'

	.col-xs-4.col-sm-6.col-md-8
		.row
			.col-xs-2
				= image_tag "icons/position.png", class: "logo_field"
			.col-xs-8
				= text_field_tag :address, 'address', value: '', placeholder: 'Adresse de ma cuisine', class: ''
			.col-xs-2
				= image_tag "icons/kitchen.png", class: "logo_field"

	.col-xs-4.col-sm-3.col-md-2
		= form_tag recipes_path do
			= hidden_field_tag(:lat, "no", "data-geo"=>"lat", required: true)
			= hidden_field_tag(:lng, "no", "data-geo"=>"lng", required: true)
			= hidden_field_tag(:formatted_address, "no", "data-geo"=>"formatted_address", required: true)
			= submit_tag "VOIR LES RECETTES", :name => nil, class: 'btn_search_recipe_green'