config/routes.rb
Rails.application.routes.draw do

  devise_for  :users, 
              :controllers => {
             #     sessions: "mydevise/sessions",
                  registrations: "mydevise/registrations"
              } 
          #    :skip => [:sessions] do
           #     get '/users/sign_in' => 'sessions#new', :as => :new_user_session
            #    post '/users/sign_in' => 'sessions#create', :as => :user_session
             #   get '/users/sign_out' => 'sessions#destroy', :as => :destroy_user_session
             # end
  resources :users, path: "user", only: [:index, :show, :destroy, :update] do
    match 'recipebook', to: 'users#recipebook', via: :get
    get '/users/sign_out' => 'devise/sessions#destroy'
    #resources :comments
  end


  resources :directions, only: [:create, :destroy, :update]

  resources :cooks do 
    resources :recipes
  end

  root "welcome#index"

  match 'add_like_recipe', to: 'like_recipes#like_recipe', via: :post
  match 'unlike_recipe', to: 'like_recipes#unlike_recipe', via: :delete
  match 'recipes', to: 'recipes#browse_recipes', via: :post
  #match 'myrecipes', to: 'recipes#my_recipes', via: :get

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in?
  		@user = User.find_by(id: current_user) 
  		@cook = Cook.find_by(user_id: @user.id)
  	end

  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
.fullpage
	.row.no-gutter.section.page1
		.font_picture{ style: "background-image: url('/assets/welcome_font/welcome#{rand(5)}.jpg')" }
		.jingle
			%h2 Apprenez dans votre cuisine !
		- if @cook.nil?
			.pub
				%h2 Vous avez un talent culinaire ?
				- if user_signed_in?
					=link_to "Devenez cook", user_path(current_user), class: 'btn_pub'
				- else
					= navbar_text 'Devenez cook', class: "btn_pub create_account no-hide"

		.search_area
			.search_adress
				= image_tag "icons/position.png", class: "icon_search"
				= text_field_tag :address, 'address', value: '', placeholder: "Chercher autour d'une adresse", class: 'address_field'
				= image_tag "icons/kitchen.png", class: "icon_cook"
			= form_tag cooks_path, :method => :get do
				= hidden_field_tag(:lat, 'no', "data-geo"=>"lat")
				= hidden_field_tag(:lng, 'no', "data-geo"=>"lng")
				= hidden_field_tag(:formatted_address, 'no', "data-geo"=>"formatted_address")
				.btn_search_cook
					.nothing
					= submit_tag "voir les cooks", class: 'search_cook'
					= image_tag "icons/chef.png", class: "icon_seach_cook"

	.row.no-gutter.section.page2
		%h2.process-title Comment ça marche ?
		.process
			.process-block
				= image_tag "process/cook.png", class: "process-picture"
				%h5 Cherchez un cook autour de chez vous
			.process-block
				= image_tag "process/menu.png", class: "process-picture"
				%h5 Choisissez votre menu et contactez-le
			.process-block
				= image_tag "process/shop.png", class: "process-picture"
				%h5 Faites les courses en gérant votre budget
			.process-block
				= image_tag "process/cooking.png", class: "process-picture"
				%h5 Cuisinez sous les conseils du cook
			.process-block
				= image_tag "process/party.png", class: "process-picture"
				%h5 Partagez ce moment en recevant chez vous !

		.strengh
			.strengh-block
				%h2 Hôtes : </br> Recevez chez vous !
				%h5 Une expérience de découverte conviviale pour un budget limité
				= image_tag "welcome_hote.png", class: "strengh-picture"
				.btn-strength
					= link_to "voir les cooks", cooks_path, class: 'btn-text'
					= image_tag "icons/button welcome/cook white.png", class: "btn-icon"

			.strengh-block
				%h2 Cooks : </br> Partagez votre talent !
				%h5 Proposez vos services à domicile sans contraintes
				= image_tag "welcome_chef.png", class: "strengh-picture"
				.btn-strength
					- if user_signed_in?
						=link_to "Devenez cook", user_path(current_user), class: 'btn-text'
					- else
						= link_to 'Devenir cook', '#', remote: :true, id: 'btn-strength', class: "btn-text"
					= image_tag "icons/button welcome/cooking white.png", class: "btn-icon"

			.strengh-block
				%h2.doubleline Les avantages cookadom
				%table
					%tbody
						%tr
							%td= image_tag "avantages/degree.png", class: 'avantage-picture'
							%td.table-text= "Contrôlez le niveau du cook et sa spécialité"
						%tr
							%td= image_tag "avantages/star.png", class: 'avantage-picture'
							%td= "Vérifiez les commentaires et avis sur le cook"
						%tr
							%td= image_tag "avantages/pay.png", class: 'avantage-picture'
							%td= "Payez le cook après la prestation en main propre"
						%tr
							%td= image_tag "avantages/calendar.png", class: 'avantage-picture'
							%td= "Gérez votre organisation directement avec le cook"
						%tr
							%td= image_tag "avantages/book.png", class: 'avantage-picture'
							%td= "Retrouvez vos recettes sur le site"
			

:javascript

	$(document).ready(function() {
	    $('#fulpage').fullpage();
	});

	$('#btn-strength').click(function() {
		$('#account').fadeIn("slow");
		$('#create-account').show();
		$('#connect-account').hide();
	});